# docker-compose.yml
version: '3.8'

services:
  bootstrap:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ROLE=bootstrap
      - CHORD_PORT=8000
    ports:
      - "8000:8000"
    networks:
      chord_net:
        ipv4_address: 172.20.0.2
    stdin_open: true
    tty: true
    
  peer:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ROLE=peer
      - BOOTSTRAP_ADDR=172.20.0.2:8000
      - CHORD_PORT=8000
    networks:
      - chord_net
    stdin_open: true
    tty: true
    depends_on:
      - bootstrap
    deploy:
      replicas: 0  # Start with 0 replicas, scale as needed

networks:
  chord_net:
    name: chord_net
    driver: bridge
    external: false
    ipam:
      config:
        - subnet: 172.20.0.0/16